### PR TITLE
feat: add PR comment triggered publish action

### PR DESCRIPTION
**Pull request by ad2ien**
- Add pull request comment triggered publish action.
- Use publish.yml actions only for nightly and release.

### CODE REVIEW

**Review by ccamel — APPROVED** [review]
Thanks! 👍

**Review by amimart — CHANGES_REQUESTED** [review]
We currently have no logic for PR publish from gradle & python, I think we can remove them until a proper implementation

**Comment by ad2ien** [comment]
> We currently have no logic for PR publish from gradle & python, I think we can remove them until a proper implementation

Done, for my information, what are the python and gradle projects we're publishing?

**Comment by amimart** [comment]
@ad2ien There the templates for [python](https://github.com/okp4/template-python-project) and [kafka processors](https://github.com/okp4/template-kafka-processor)

**Review by amimart — APPROVED** [review]

**Pull request merged**
